```python
"""
Generate engineering report plots from JSON benchmark results.

Expected input:
    results_infertutor/*.json

Expected output:
    plots/*.png

Each JSON file is expected to contain at least:
    {
        "config": {
            "label": "...",
            "users": ...,
            "total_gpus": ...
        },
        "results": {
            "aggregate_stream_chunks_per_s": ...,
            "error_rate": ...,
            "ttft_p95_ms": ...,
            "itl_p95_ms": ...
        }
    }

The script loads all benchmark runs, computes a custom score, and writes
six plots that summarize performance behavior across text and multimodal runs.
"""

import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------

# Directory containing this script.
# Using __file__ keeps the script portable because paths are relative to
# the script location, not the directory from which the script is executed.
ROOT = Path(__file__).parent

# Directory where benchmark JSON files are expected to live.
RESULTS = ROOT / "results_infertutor"

# Directory where generated plots will be written.
PLOTS = ROOT / "plots"

# Create the plots directory if it does not already exist.
# exist_ok=True avoids an error if the directory is already present.
PLOTS.mkdir(exist_ok=True)


# ---------------------------------------------------------------------------
# Global matplotlib defaults
# ---------------------------------------------------------------------------

# These settings apply to every figure generated by this script.
# figure.dpi controls display/rendering resolution.
# savefig.dpi controls output PNG resolution.
# font.size controls default text size across plots.
plt.rcParams.update(
    {
        "figure.dpi": 110,
        "savefig.dpi": 140,
        "font.size": 11,
    }
)


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_all():
    """
    Load every JSON benchmark result from results_infertutor/.

    Returns:
        dict:
            Mapping from run label to the loaded benchmark payload.

            Example:
                {
                    "baseline-text": {
                        "file": "baseline-text.json",
                        "config": {...},
                        "results": {...}
                    }
                }

    Important behavior:
        The dictionary key is data["config"]["label"].

        If multiple JSON files contain the same label, the later file in the
        sorted file order will overwrite the earlier one. This matches the
        original behavior, but it means labels should ideally be unique.
    """

    # Store all loaded runs here.
    runs = {}

    # Iterate through all JSON files in deterministic filename order.
    for f in sorted(RESULTS.glob("*.json")):
        # Read the file as text and parse it as JSON.
        data = json.loads(f.read_text())

        # Use the human-readable config label as the dictionary key.
        label = data["config"]["label"]

        # Store the file name alongside the original JSON payload.
        # The **data spread keeps all original top-level fields.
        runs[label] = {
            "file": f.name,
            **data,
        }

    return runs


# ---------------------------------------------------------------------------
# Scoring function
# ---------------------------------------------------------------------------

def score(data):
    """
    Compute the custom engineering-report score for a single benchmark run.

    Score intuition:
        Bigger is better.

        The score rewards:
            - higher streaming throughput
            - more concurrent users

        The score penalizes:
            - higher error rate
            - higher p95 time-to-first-token
            - higher p95 inter-token latency
            - more GPUs

    Formula:
        goodput = throughput * (1 - error_rate)

        score = goodput * users / (ttft_seconds * itl_seconds * total_gpus)

    Args:
        data:
            One loaded benchmark run containing "config" and "results".

    Returns:
        float:
            Computed score.
    """

    # Pull config and results into shorter local variables.
    c = data["config"]
    r = data["results"]

    # Goodput is throughput adjusted downward by error rate.
    # max(0, ...) prevents negative goodput if error_rate somehow exceeds 1.
    goodput = r["aggregate_stream_chunks_per_s"] * max(0, 1 - r["error_rate"])

    # Convert TTFT from milliseconds to seconds.
    # Use a tiny floor value to avoid division by zero.
    ttft = max(r["ttft_p95_ms"] / 1000, 0.001)

    # Convert ITL from milliseconds to seconds.
    # Use a tiny floor value to avoid division by zero.
    itl = max(r["itl_p95_ms"] / 1000, 0.001)

    # Protect against division by zero if total_gpus is missing or set to 0.
    gpu_count = max(c["total_gpus"], 1)

    # Final score.
    return goodput * c["users"] / (ttft * itl * gpu_count)


# ---------------------------------------------------------------------------
# Plot 1: Text-track knee map
# ---------------------------------------------------------------------------

def plot_text_knee(runs):
    """
    Plot text-track concurrency sweep.

    Goal:
        Show how p95 TTFT and throughput change as concurrent users increase.

    Interpretation:
        The "knee" is the point where adding users starts causing latency to
        rise sharply. In this benchmark, the knee is visually highlighted
        around 60 to 100 users.
    """

    # Ordered list of labels and their intended displayed user counts.
    # Some labels are manually selected because the report wants a specific
    # clean run for each user count.
    points = [
        ("smoke", 5),
        ("baseline-text", 50),
        ("sweep-60u", 60),
        ("sweep-70u", 70),
        ("sweep-80u", 80),
        ("sweep-90u", 90),
        ("sweep-100u", 100),
        ("sweep-300u", 300),
        ("sweep-400u", 400),
        ("sweep-500u", 500),
        ("sweep-600u", 600),
    ]

    # X-axis values.
    users = []

    # Left Y-axis values.
    ttft = []

    # Right Y-axis values.
    throughput = []

    # Build the plotted series.
    for label, user_count in points:
        # Find the run for this label.
        # Because runs is keyed by label, this usually returns either 0 or 1 item.
        candidates = [run for key, run in runs.items() if key == label]

        # Skip labels that are not present in the loaded results.
        if not candidates:
            continue

        # Preserve the original script behavior.
        # If candidates ever contains more than one item, choose the first one.
        chosen = candidates[0]

        # Append the values that will be plotted.
        users.append(user_count)
        ttft.append(chosen["results"]["ttft_p95_ms"])
        throughput.append(chosen["results"]["aggregate_stream_chunks_per_s"])

    # Create a figure and the first axis.
    fig, ax1 = plt.subplots(figsize=(11, 6.5))

    # Create a second Y-axis sharing the same X-axis.
    # This lets us plot latency and throughput on different scales.
    ax2 = ax1.twinx()

    # Explicit colors make the two axes easier to visually separate.
    color_ttft = "#d62728"
    color_thr = "#2ca02c"

    # Plot TTFT on the left Y-axis.
    ax1.plot(
        users,
        ttft,
        "o-",
        color=color_ttft,
        lw=2.4,
        ms=9,
        label="TTFT p95 (ms)",
        zorder=3,
    )

    # Plot throughput on the right Y-axis.
    ax2.plot(
        users,
        throughput,
        "s--",
        color=color_thr,
        lw=2,
        ms=8,
        label="Throughput (chunks/s)",
        zorder=2,
    )

    # Use log scale because TTFT can jump by orders of magnitude.
    ax1.set_yscale("log")

    # Axis labels.
    ax1.set_xlabel("Concurrent users", fontsize=12)
    ax1.set_ylabel("TTFT p95 (ms, log scale)", color=color_ttft, fontsize=12)
    ax2.set_ylabel("Throughput (chunks/s)", color=color_thr, fontsize=12)

    # Match tick label colors with each axis line color.
    ax1.tick_params(axis="y", labelcolor=color_ttft)
    ax2.tick_params(axis="y", labelcolor=color_thr)

    # Highlight the knee zone where latency starts to bend upward.
    ax1.axvspan(
        60,
        100,
        alpha=0.18,
        color="orange",
        label="The knee (60-100u)",
    )

    # Annotate the baseline point if it exists.
    if 50 in users:
        i = users.index(50)
        ax1.annotate(
            "  baseline\n  50u, 726ms",
            (users[i], ttft[i]),
            textcoords="offset points",
            xytext=(10, -22),
            fontsize=9.5,
            color=color_ttft,
        )

    # Annotate the 100-user jump if it exists.
    if 100 in users:
        i = users.index(100)
        ax1.annotate(
            "100u\n10× TTFT jump\nvs 60u",
            (users[i], ttft[i]),
            textcoords="offset points",
            xytext=(15, -5),
            fontsize=9.5,
            color="darkred",
            fontweight="bold",
        )

    # Main title.
    ax1.set_title(
        "Text-Track Knee Map — Default Knobs, 1 GPU\n"
        "TTFT p95 stays flat through 60u, then explodes by 100u",
        fontsize=13,
        pad=14,
    )

    # Add a light grid for readability.
    ax1.grid(True, alpha=0.25, ls="--")

    # Force stable X-axis ticks so the plot is easy to compare across runs.
    ax1.set_xticks([0, 50, 100, 200, 300, 400, 500, 600])

    # Collect legends from both axes.
    lines1, labels1 = ax1.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()

    # Draw one combined legend.
    ax1.legend(
        lines1 + lines2,
        labels1 + labels2,
        loc="center right",
        framealpha=0.95,
    )

    # Prevent labels and titles from being clipped.
    fig.tight_layout()

    # Save output.
    out = PLOTS / "01_text_knee.png"
    fig.savefig(out, bbox_inches="tight")

    # Close figure to avoid memory buildup when generating many plots.
    plt.close(fig)

    print(f"Wrote {out}")


# ---------------------------------------------------------------------------
# Plot 2: Knob ablations
# ---------------------------------------------------------------------------

def plot_knob_ablations(runs):
    """
    Plot text-track knob ablation scores.

    Goal:
        Compare several configuration changes against the baseline.

    Interpretation:
        The plot shows that compiled mode is the only winning knob among the
        listed options, while widening-related knobs underperform.
    """

    # Each tuple contains:
    #   display label for plot,
    #   key used to look up the run,
    #   bar color.
    items = [
        ("baseline\n(50u, default)", "baseline-text", "#1f77b4"),
        ("--no-prefix-cache\n(70u)", "noprefix-70u", "#d62728"),
        ("--no-chunked-prefill\n(70u)", "nochunked-70u", "#ff7f0e"),
        ("--max-seqs 64\n(70u)", "seqs64-70u", "#d62728"),
        ("--max-batch-tokens 8192\n(70u)", "batch8k-70u", "#d62728"),
        ("--replicas 2 (eager)\n(140u, 2 GPU)", "scale-r2-140u", "#d62728"),
        ("--no-fast-boot\n(compiled, 70u)", "compiled-70u", "#2ca02c"),
    ]

    labels = []
    scores = []
    colors = []

    # Convert each run into a score in millions.
    for display_label, key, color in items:
        # Only include runs that are present in the result set.
        if key in runs:
            labels.append(display_label)
            scores.append(score(runs[key]) / 1e6)
            colors.append(color)

    # Create bar chart.
    fig, ax = plt.subplots(figsize=(13, 6.5))
    bars = ax.bar(
        labels,
        scores,
        color=colors,
        edgecolor="black",
        linewidth=0.6,
    )

    # Use log scale because ablation scores can vary sharply.
    ax.set_yscale("log")

    # Axis label and title.
    ax.set_ylabel("Score (millions, log scale)", fontsize=12)
    ax.set_title(
        "Text-Track Knob A/Bs at 70 Users — Compiled Mode is the Only Win\n"
        "Bigger is better. All 'widening' knobs scored worse than baseline.",
        fontsize=13,
        pad=14,
    )

    # Horizontal grid only.
    ax.grid(True, axis="y", alpha=0.25, ls="--")

    # Label every bar with its numeric score.
    for bar, val in zip(bars, scores):
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            val * 1.12,
            f"{val:.2f}M",
            ha="center",
            fontsize=10.5,
            fontweight="bold",
        )

    # Keep labels horizontal and readable.
    plt.setp(ax.get_xticklabels(), rotation=0, fontsize=9.5)

    # Final layout and save.
    fig.tight_layout()
    out = PLOTS / "02_text_knob_ablations.png"
    fig.savefig(out, bbox_inches="tight")
    plt.close(fig)

    print(f"Wrote {out}")


# ---------------------------------------------------------------------------
# Plot 3: Compiled vs eager
# ---------------------------------------------------------------------------

def plot_compiled_vs_eager(runs):
    """
    Compare eager mode against compiled mode for both tracks.

    Text track comparison:
        baseline-text at 50 users
        compiled-70u at 70 users

    Multimodal track comparison:
        m-50u at 50 users
        m-compiled-50u at 50 users

    The chart groups TTFT, ITL, and throughput side-by-side.
    """

    # Create two side-by-side plots:
    #   left: text track
    #   right: multimodal track
    fig, axes = plt.subplots(1, 2, figsize=(13, 5.8))

    # Width of each grouped bar.
    w = 0.25

    # -----------------------------------------------------------------------
    # Left plot: text track
    # -----------------------------------------------------------------------

    ax = axes[0]

    configs = ["Eager\n(50u)", "Compiled\n(70u)"]

    # Pull TTFT p95 in milliseconds.
    ttft = [
        runs["baseline-text"]["results"]["ttft_p95_ms"],
        runs["compiled-70u"]["results"]["ttft_p95_ms"],
    ]

    # Pull ITL p95 in milliseconds.
    itl = [
        runs["baseline-text"]["results"]["itl_p95_ms"],
        runs["compiled-70u"]["results"]["itl_p95_ms"],
    ]

    # Pull aggregate throughput in chunks per second.
    thr = [
        runs["baseline-text"]["results"]["aggregate_stream_chunks_per_s"],
        runs["compiled-70u"]["results"]["aggregate_stream_chunks_per_s"],
    ]

    # X locations for the two grouped categories.
    x = np.arange(2)

    # Plot TTFT directly.
    ax.bar(
        x - w,
        ttft,
        w,
        label="TTFT p95 (ms)",
        color="#d62728",
    )

    # Multiply ITL by 30 so it is visually comparable on the same axis.
    # This is a visualization scaling trick, not a metric change.
    ax.bar(
        x,
        [value * 30 for value in itl],
        w,
        label="ITL p95 × 30 (ms)",
        color="#ff7f0e",
    )

    # Plot throughput directly.
    ax.bar(
        x + w,
        thr,
        w,
        label="Throughput (chunks/s)",
        color="#2ca02c",
    )

    ax.set_xticks(x)
    ax.set_xticklabels(configs)

    ax.set_title(
        "Text Track\n"
        "Compiled mode at 70u beats eager at 50u on every metric",
        fontsize=12,
    )

    ax.grid(True, axis="y", alpha=0.25, ls="--")
    ax.legend(loc="upper left", fontsize=9.5)

    # -----------------------------------------------------------------------
    # Right plot: multimodal track
    # -----------------------------------------------------------------------

    ax = axes[1]

    configs = ["Eager\n(50u)", "Compiled\n(50u)"]

    ttft = [
        runs["m-50u"]["results"]["ttft_p95_ms"],
        runs["m-compiled-50u"]["results"]["ttft_p95_ms"],
    ]

    itl = [
        runs["m-50u"]["results"]["itl_p95_ms"],
        runs["m-compiled-50u"]["results"]["itl_p95_ms"],
    ]

    thr = [
        runs["m-50u"]["results"]["aggregate_stream_chunks_per_s"],
        runs["m-compiled-50u"]["results"]["aggregate_stream_chunks_per_s"],
    ]

    x = np.arange(2)

    ax.bar(
        x - w,
        ttft,
        w,
        label="TTFT p95 (ms)",
        color="#d62728",
    )

    ax.bar(
        x,
        [value * 30 for value in itl],
        w,
        label="ITL p95 × 30 (ms)",
        color="#ff7f0e",
    )

    ax.bar(
        x + w,
        thr,
        w,
        label="Throughput (chunks/s)",
        color="#2ca02c",
    )

    ax.set_xticks(x)
    ax.set_xticklabels(configs)

    ax.set_title(
        "Multimodal Track\n"
        "Compiled mode wins here too — contrary to runbook warning!",
        fontsize=12,
    )

    ax.grid(True, axis="y", alpha=0.25, ls="--")
    ax.legend(loc="upper left", fontsize=9.5)

    # Overall title for the two-panel figure.
    fig.suptitle(
        "Compiled Mode (`--no-fast-boot`) is the Dominant Knob in BOTH Tracks",
        fontsize=14,
        y=1.02,
    )

    fig.tight_layout()
    out = PLOTS / "03_compiled_vs_eager.png"
    fig.savefig(out, bbox_inches="tight")
    plt.close(fig)

    print(f"Wrote {out}")


# ---------------------------------------------------------------------------
# Plot 4: Final summary against references
# ---------------------------------------------------------------------------

def plot_final_summary(runs):
    """
    Compare final submission scores against workshop reference baselines.

    This plot includes:
        - FINAL-mixed submission
        - FINAL text submission
        - 2-replica mixed reference baseline
        - 4-replica mixed reference baseline
    """

    # Each tuple contains:
    #   display label,
    #   run key, or None for manually computed references,
    #   bar color.
    items = [
        ("FINAL-mixed\n(Track 1, 180s)\nMy submission", "FINAL-mixed", "#2ca02c"),
        ("FINAL_text_70u\n(Track 2, 180s)", "FINAL", "#1f77b4"),
        ("Reference 2r mixed\n(workshop baseline)", None, "#888888"),
        ("Reference 4r mixed\n(workshop baseline)", None, "#888888"),
    ]

    # Reference baseline scores computed from runbook table values.
    #
    # 2-replica mixed:
    #   TTFT = 1169 ms
    #   ITL = 28.7 ms
    #   throughput = 2243 chunks/s
    #   users = 100
    #   GPUs = 2
    ref_2r = 2243 * 100 * 1.0 / (1.169 * 0.0287 * 2)

    # 4-replica mixed:
    #   TTFT = 898 ms
    #   ITL = 38.1 ms
    #   throughput = 2756 chunks/s
    #   users = 120
    #   GPUs = 4
    ref_4r = 2756 * 120 * 1.0 / (0.898 * 0.0381 * 4)

    labels = []
    scores = []
    colors = []

    # Build the plotted values.
    for display_label, key, color in items:
        labels.append(display_label)
        colors.append(color)

        # For real runs, compute score from JSON.
        if key and key in runs:
            scores.append(score(runs[key]) / 1e6)

        # For reference rows, use the manually computed references.
        elif "2r" in display_label:
            scores.append(ref_2r / 1e6)

        elif "4r" in display_label:
            scores.append(ref_4r / 1e6)

        # Fallback for missing data.
        else:
            scores.append(0)

    # Create bar chart.
    fig, ax = plt.subplots(figsize=(11, 6))
    bars = ax.bar(
        labels,
        scores,
        color=colors,
        edgecolor="black",
        linewidth=0.6,
    )

    ax.set_ylabel("Score (millions)", fontsize=12)
    ax.set_title(
        "Final Submission Comparison — Both Tracks Crush the Reference Baselines",
        fontsize=13,
        pad=14,
    )
    ax.grid(True, axis="y", alpha=0.25, ls="--")

    # Add value labels above bars.
    for bar, val in zip(bars, scores):
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            val + max(scores) * 0.015,
            f"{val:.1f}M",
            ha="center",
            fontsize=11,
            fontweight="bold",
        )

    # Annotate the ratio of FINAL-mixed to the 2-replica reference.
    final_mixed = score(runs["FINAL-mixed"]) / 1e6

    ax.annotate(
        f"{final_mixed / (ref_2r / 1e6):.1f}× the 2-replica\nreference baseline",
        xy=(0, final_mixed),
        xytext=(0.4, final_mixed * 0.85),
        fontsize=10,
        color="darkgreen",
        fontweight="bold",
        arrowprops={
            "arrowstyle": "->",
            "color": "darkgreen",
            "lw": 1.4,
        },
    )

    fig.tight_layout()
    out = PLOTS / "04_final_summary.png"
    fig.savefig(out, bbox_inches="tight")
    plt.close(fig)

    print(f"Wrote {out}")


# ---------------------------------------------------------------------------
# Plot 5: Duration lesson
# ---------------------------------------------------------------------------

def plot_duration_lesson(runs):
    """
    Compare 90-second tests against 180-second final runs.

    Goal:
        Show that short tests can be misleading.

    In this report:
        - Text track scores lower at 180s because tail behavior emerges.
        - Multimodal track scores higher at 180s because steady-state improves.
    """

    # Text track:
    #   90s snapshot is compiled-70u.
    #   180s final is FINAL.
    text_90s = score(runs["compiled-70u"]) / 1e6
    text_180s = score(runs["FINAL"]) / 1e6

    # Multimodal track:
    #   90s snapshot is m-compiled-50u.
    #   180s final is FINAL-mixed.
    mm_90s = score(runs["m-compiled-50u"]) / 1e6
    mm_180s = score(runs["FINAL-mixed"]) / 1e6

    fig, ax = plt.subplots(figsize=(11, 6.5))

    # Two groups:
    #   index 0 = text
    #   index 1 = multimodal
    x = np.arange(2)

    # Width of each bar.
    w = 0.35

    # Left bar in each group: 90-second result.
    bars1 = ax.bar(
        x - w / 2,
        [text_90s, mm_90s],
        w,
        label="90 second test",
        color="#9ecae1",
    )

    # Right bar in each group: 180-second final.
    bars2 = ax.bar(
        x + w / 2,
        [text_180s, mm_180s],
        w,
        label="180 second test (FINAL)",
        color="#3182bd",
    )

    ax.set_xticks(x)
    ax.set_xticklabels(
        [
            "Text Track\n(compiled-70u → FINAL_text_70u)",
            "Multimodal Track\n(m-compiled-50u → FINAL-mixed)",
        ],
        fontsize=11,
    )

    ax.set_ylabel("Score (millions)", fontsize=12)
    ax.set_title(
        "The Duration Lesson: Short Tests Can Mislead — BOTH Ways\n"
        "Text 180s scored LOWER (tail emerged); "
        "Multimodal 180s scored HIGHER (steady-state was better).",
        fontsize=12.5,
        pad=14,
    )

    ax.grid(True, axis="y", alpha=0.25, ls="--")
    ax.legend(loc="upper right", fontsize=10.5)

    # Label 90-second bars.
    for bar, val in zip(bars1, [text_90s, mm_90s]):
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            val + 1.5,
            f"{val:.1f}M",
            ha="center",
            fontsize=10.5,
            fontweight="bold",
        )

    # Label 180-second bars.
    for bar, val in zip(bars2, [text_180s, mm_180s]):
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            val + 1.5,
            f"{val:.1f}M",
            ha="center",
            fontsize=10.5,
            fontweight="bold",
        )

    # Delta annotation for text track.
    ax.annotate(
        f"Δ {(text_180s / text_90s - 1) * 100:.0f}%",
        xy=(x[0], max(text_90s, text_180s)),
        xytext=(x[0], max(text_90s, text_180s) + 10),
        ha="center",
        fontsize=11,
        color="darkred",
        fontweight="bold",
    )

    # Delta annotation for multimodal track.
    ax.annotate(
        f"Δ +{(mm_180s / mm_90s - 1) * 100:.0f}%",
        xy=(x[1], max(mm_90s, mm_180s)),
        xytext=(x[1], max(mm_90s, mm_180s) + 10),
        ha="center",
        fontsize=11,
        color="darkgreen",
        fontweight="bold",
    )

    fig.tight_layout()
    out = PLOTS / "05_duration_lesson.png"
    fig.savefig(out, bbox_inches="tight")
    plt.close(fig)

    print(f"Wrote {out}")


# ---------------------------------------------------------------------------
# Plot 6: Score decomposition
# ---------------------------------------------------------------------------

def plot_score_decomposition(runs):
    """
    Render a text-only plot explaining the score calculation for FINAL-mixed.

    This is useful for reports because it makes the formula auditable and
    shows how throughput, users, latency, error rate, and GPU count combine.

    Note:
        This function intentionally preserves the original script's behavior.

        The shared score() function applies error_rate once through goodput:

            goodput = throughput * (1 - error_rate)

        This decomposition then multiplies by (1 - error_rate) again in the
        numerator. That means error_rate is applied twice here.

        If the goal is to exactly match score(), remove the second
        (1 - error_rate) factor from num.
    """

    # Extract final mixed result payload.
    final = runs["FINAL-mixed"]["results"]

    # Extract final mixed config payload.
    c = runs["FINAL-mixed"]["config"]

    # Compute error-adjusted throughput.
    goodput = final["aggregate_stream_chunks_per_s"] * (1 - final["error_rate"])

    # Convert latency metrics from milliseconds to seconds.
    ttft_s = final["ttft_p95_ms"] / 1000
    itl_s = final["itl_p95_ms"] / 1000

    # Preserve original decomposition behavior.
    # Important:
    #   This applies (1 - error_rate) a second time.
    num = goodput * c["users"] * (1 - final["error_rate"])

    # Denominator penalizes latency and GPU count.
    den = ttft_s * itl_s * c["total_gpus"]

    # Final decomposed score.
    final_score = num / den

    # Create a blank figure.
    fig, ax = plt.subplots(figsize=(11, 5))

    # Hide axes because this is a formula card, not a data plot.
    ax.axis("off")

    # Build the text block shown in the figure.
    text = (
        "FINAL-mixed Score Decomposition (Track 1 Submission)\n"
        "─────────────────────────────────────────────────────\n\n"
        "   Score = goodput × users × (1 − error_rate)\n"
        "           ────────────────────────────────────\n"
        "           p95_TTFT_s × p95_ITL_s × GPU_count\n\n"
        f"   Numerator   = {goodput:>7.0f}    × {c['users']:>3}  × "
        f"{(1 - final['error_rate']):.4f}\n"
        f"                = {num:>12,.0f}\n\n"
        f"   Denominator = {ttft_s:>7.4f}s × {itl_s:>7.5f}s × "
        f"{c['total_gpus']}\n"
        f"                = {den:>12.6f}\n\n"
        f"   SCORE       = {final_score:>12,.0f}\n"
        f"               = {final_score / 1e6:.2f} M"
    )

    # Draw the text block in monospace so columns align.
    ax.text(
        0.05,
        0.5,
        text,
        fontfamily="monospace",
        fontsize=12,
        verticalalignment="center",
        transform=ax.transAxes,
    )

    fig.tight_layout()
    out = PLOTS / "06_score_decomposition.png"
    fig.savefig(out, bbox_inches="tight")
    plt.close(fig)

    print(f"Wrote {out}")


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def main():
    """
    Load all benchmark runs and generate every report plot.

    Execution order:
        1. Load all JSON files.
        2. Print number of loaded runs.
        3. Generate six report plots.
        4. Print final output directory.
    """

    # Load all runs from results_infertutor/*.json.
    runs = load_all()

    # Print a quick sanity check.
    print(f"Loaded {len(runs)} runs")

    # Plot 1: text-track concurrency knee.
    plot_text_knee(runs)

    # Plot 2: text-track knob ablations.
    plot_knob_ablations(runs)

    # Plot 3: compiled vs eager comparison.
    plot_compiled_vs_eager(runs)

    # Plot 4: final submission vs references.
    plot_final_summary(runs)

    # Plot 5: 90-second vs 180-second lesson.
    plot_duration_lesson(runs)

    # Plot 6: score formula decomposition.
    plot_score_decomposition(runs)

    # Final status message.
    print("\nAll plots written to plots/")


# This guard ensures main() only runs when this file is executed directly.
# It prevents the plotting workflow from running if another script imports
# this file as a module.
if __name__ == "__main__":
    main()
```
